### ISSUE TITLE
Refactorisation et centralisation de la gestion des versions Terraform

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#12]
Imported from GitLab:

# Refactorisation et centralisation de la gestion des versions Terraform

## Scope

Infrastructure Terraform (Modules, Providers, CI/CD Pipeline GitLab)

## Description fonctionnelle

Améliorer la maintenabilité et la cohérence de l'infrastructure IaC en créant une gestion centralisée des versions Terraform et des providers via des fichiers `versions.tf` dédiés. Cette refactorisation permettra une meilleure traçabilité des versions, une maintenance simplifiée et une validation automatisée dans la pipeline GitLab CI/CD.

### Étape 1 : Création du fichier `versions.tf` central dans le module globals

Créer `terraform/globals/versions.tf` :

```hcl
# =============================================================================
# GESTION CENTRALISÉE DES VERSIONS TERRAFORM ET PROVIDERS
# =============================================================================

terraform {
  required_version = ">= 1.12.1, < 2.0.0"
  
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# Variables locales pour centraliser les contraintes de versions
locals {
  # Contraintes Terraform et Providers (pour référence par les environnements)
  terraform_constraints = {
    terraform_version = ">= 1.12.1, < 2.0.0"
    provider_versions = {
      local = "~> 2.5"
      null  = "~> 3.2"
    }
  }
  
  # Versions exactes des outils (existant, à conserver dans main.tf)
  tool_versions = {
    terraform     = "1.12.1"
    k3s          = "v1.33.1+k3s1"
    helm         = "3.18.1"
    ansible      = "2.18.6"
    docker       = "28.2.1"
    ubuntu       = "24.04"
    postgresql   = "17.5"
    gitlab_runner = "17.11.1"
  }
}
```

### Étape 2 : Mise à jour du module globals

Modifier `terraform/globals/main.tf` pour référencer les nouvelles variables de versions et supprimer la section versions existante.

### Étape 3 : Création des fichiers `versions.tf` pour les environnements

Créer `terraform/environments/dev/versions.tf` et `terraform/environments/prod/versions.tf` qui héritent des contraintes centralisées.

### Étape 4 : Ajout d'outputs pour les versions dans globals

Exposer les contraintes de versions via les outputs du module globals pour utilisation par les environnements.

### Étape 5 : Intégration dans la pipeline GitLab CI/CD

Ajouter une étape de validation spécifique aux versions dans `.gitlab-ci.yml` :

```yaml
validate_versions:
  stage: validate
  script:
    - echo "🔍 Validation des contraintes de versions..."
    - find terraform/ -name "versions.tf" -exec terraform fmt -check=true -diff=true {} \;
    - terraform -chdir=terraform/globals validate
```

### Prérequis techniques

- Préservation de la compatibilité avec l'infrastructure existante
- Conservation des versions actuelles des outils (pas de breaking change)
- Tests sur l'environnement dev avant application en prod

### Fonctionnels

- Les contraintes de versions Terraform et providers sont centralisées dans le module globals
- Les environnements dev et prod utilisent des contraintes cohérentes
- La pipeline GitLab valide automatiquement les fichiers de versions
- Aucune régression sur les déploiements existants

### Techniques

- Respect des conventions HashiCorp (séparation `versions.tf`)
- Documentation des changements dans les fichiers concernés
- Conservation de la rétrocompatibilité
- Validation syntaxique automatisée dans la CI/CD
- Fichiers correctement formatés (`terraform fmt`)

## Criticité

**Moyenne** - Amélioration significative de la maintenabilité sans urgence critique. Cette refactorisation facilitera les futures mises à jour de versions et réduira les risques d'incohérence entre environnements.

## Labels recommandés

Infrastructure, Terraform, GitLab CI/CD, Maintenance, Best-Practices

## Estimation du temps nécessaire

**6 heures** pour un développeur/ingénieur confirmé (incluant tests et validation)

## Décomposition des tâches

1. **Analyse et planning** (1h) : Étude de l'existant et définition de la stratégie de migration
2. **Création du module versions globals** (2h) : Développement et tests du fichier central
3. **Mise à jour des environnements** (2h) : Adaptation de dev et prod
4. **Intégration CI/CD** (1h) : Ajout des validations dans la pipeline GitLab

## Liens utiles

- [Terraform Version Constraints](https://developer.hashicorp.com/terraform/language/expressions/version-constraints)
- [HashiCorp Configuration Language Style Guide](https://developer.hashicorp.com/terraform/language/syntax/style)
- Documentation GitLab interne : `terraform/globals/main.tf`
- Pipeline actuelle : `.gitlab-ci.yml`

## Points d'attention

- **Cohérence cross-environnements** : S'assurer que dev et prod utilisent exactement les mêmes contraintes
- **Backward compatibility** : Aucun impact sur les déploiements en cours
- **Validation progressive** : Tester d'abord sur dev, puis appliquer sur prod
- **Documentation** : Mettre à jour le README.md pour expliquer la nouvelle structure

### terraform/environments/dev/versions.tf

```hcl
# =============================================================================
# CONTRAINTES DE VERSIONS - ENVIRONNEMENT DÉVELOPPEMENT
# =============================================================================

terraform {
  required_version = ">= 1.12.1, < 2.0.0"
  
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}
```

### Modification du .gitlab-ci.yml (section validate)

```yaml
# Validation des versions Terraform
validate_versions:
  stage: validate
  image: alpine:latest
  <<: *install_terraform
  script:
    - echo "🔍 Validation des contraintes de versions Terraform..."
    
    # Vérification du formatage des fichiers versions.tf
    - |
      for versions_file in $(find terraform/ -name "versions.tf"); do
        echo "📋 Validation du formatage: $versions_file"
        terraform fmt -check=true -diff=true "$versions_file"
        if [ $? -ne 0 ]; then
          echo "❌ Fichier mal formaté: $versions_file"
          exit 1
        fi
      done
    
    # Validation de la syntaxe du module globals
    - echo "📋 Validation syntaxique du module globals..."
    - cd terraform/globals && terraform init -backend=false && terraform validate
    
    # Validation de la cohérence entre environnements
    - echo "📋 Vérification de la cohérence des versions..."
    - |
      dev_versions=$(grep -A 10 "required_version" terraform/environments/dev/versions.tf | head -1)
      prod_versions=$(grep -A 10 "required_version" terraform/environments/prod/versions.tf | head -1)
      
      if [ "$dev_versions" != "$prod_versions" ]; then
        echo "❌ Incohérence de versions entre dev et prod"
        exit 1
      fi
      
      echo "✅ Versions cohérentes entre tous les environnements"
    
    - echo "✅ Validation des versions terminée avec succès"
  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags:
    - terraform
```

Cette tâche permettra d'améliorer significativement la structure et la maintenabilité de votre infrastructure Terraform tout en respectant les best practices HashiCorp.
