### ISSUE TITLE
Créer des job templates spécifiques par environnement

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#18]
Imported from GitLab:

### Tâche 7

Créer des job templates spécifiques par environnement

**Scope** : CI/CD Pipeline GitLab

**Description fonctionnelle** :
Développer des templates de jobs spécialisés pour les environnements dev et prod afin de centraliser leurs configurations spécifiques.

**Description technique** :
- Dans `.gitlab/ci/includes/templates.yml`, ajouter :
  - `.dev_environment` : Configuration commune jobs dev
  - `.prod_environment` : Configuration commune jobs prod avec sécurité renforcée
- Configurations à inclure :
```yaml
.dev_environment:
  variables:
    ENV: dev
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

.prod_environment:
  variables:
    ENV: prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  before_script:
    - echo "⚠️ PRODUCTION DEPLOYMENT"
    - # Vérifications sécurité supplémentaires
```
- Refactoriser les jobs existants pour utiliser ces templates
- Documenter les différences dev/prod

**Critères d'acceptation** :
- Fonctionnel : Templates appliqués réduisent la duplication
- Technique : Séparation claire des configurations par environnement

**Criticité** : Moyenne - Optimisation de la structure

**Labels recommandés** : Infrastructure, GitLab CI/CD, Refactoring

**Estimation du temps nécessaire** : 3 heures

**Liens utiles** : Patterns de configuration dev/prod actuels

---
