### ISSUE TITLE
Modulariser les jobs Terraform dans un fichier dédié

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#20]
Imported from GitLab:

### Tâche 5

Modulariser les jobs Terraform dans un fichier dédié

**Scope** : CI/CD Pipeline GitLab

**Description fonctionnelle** :
Extraire tous les jobs Terraform (validate, plan, apply) du pipeline principal vers un module dédié pour améliorer l'organisation et la maintenance.

**Description technique** :
- Créer `.gitlab/ci/includes/terraform.yml`
- Migrer les jobs depuis le pipeline actuel :
  - `validate_versions`
  - `validate`
  - `plan_dev`, `plan_prod`
  - `apply_dev`, `apply_prod`
- Utiliser les templates créés en tâche [303]
- Conserver exactement la même logique métier
- Structure suggérée :
```yaml
# Terraform Jobs Module

validate_versions:
  extends: .terraform_base
  stage: validate
  # ... job content

.plan_template:
  extends: .terraform_base
  stage: plan
  # ... common plan logic

plan_dev:
  extends: .plan_template
  variables:
    ENV: dev
  # ... specific dev config
```

**Critères d'acceptation** :
- Fonctionnel : Tous les jobs Terraform fonctionnent identiquement
- Technique : Code factorisé via templates, pas de duplication

**Criticité** : Haute - Jobs critiques pour le déploiement infrastructure

**Labels recommandés** : Infrastructure, GitLab CI/CD, Terraform, Refactoring

**Estimation du temps nécessaire** : 4 heures

**Liens utiles** : Structure actuelle dans .gitlab-ci.yml

---
