### ISSUE TITLE
Migrer le fichier .gitlab-ci.yml principal vers la structure modulaire

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#21]
Imported from GitLab:

### Tâche 4

Migrer le fichier .gitlab-ci.yml principal vers la structure modulaire

**Scope** : CI/CD Pipeline GitLab

**Description fonctionnelle** :
Transformer le fichier .gitlab-ci.yml monolithique actuel en un fichier principal léger qui inclut les modules créés précédemment.

**Description technique** :
- Sauvegarder l'actuel `.gitlab-ci.yml` en `.gitlab-ci.yml.backup`
- Créer nouveau `.gitlab-ci.yml` minimaliste (~50-100 lignes) :
```yaml
# Pipeline GitLab CI/CD - Infrastructure as Code
# Version: 3.0.0 - Modularisé

include:
  - local: '.gitlab/ci/includes/variables.yml'
  - local: '.gitlab/ci/includes/templates.yml'
  - local: '.gitlab/ci/includes/terraform.yml'
  - local: '.gitlab/ci/includes/ansible.yml'
  - local: '.gitlab/ci/includes/sync.yml'
  - local: '.gitlab/ci/includes/cleanup.yml'

stages:
  - validate
  - plan
  - apply
  - deploy
  - sync
  - cleanup
```
- Documenter la nouvelle structure en en-tête
- Tester que le pipeline se charge correctement

**Critères d'acceptation** :
- Fonctionnel : Pipeline charge tous les modules sans erreur
- Technique : Fichier principal <100 lignes, structure claire

**Criticité** : Haute - Point d'entrée du nouveau pipeline modulaire

**Labels recommandés** : Infrastructure, GitLab CI/CD, Refactoring

**Estimation du temps nécessaire** : 2 heures

**Liens utiles** : GitLab CI/CD include documentation

---
