### ISSUE TITLE
Créer les templates de jobs génériques réutilisables

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#22]
Imported from GitLab:

### Tâche 3

Créer les templates de jobs génériques réutilisables

**Scope** : CI/CD Pipeline GitLab

**Description fonctionnelle** :
Développer des templates de jobs GitLab CI/CD génériques pour factoriser le code commun et faciliter la création de nouveaux jobs.

**Description technique** :
- Créer `.gitlab/ci/includes/templates.yml`
- Extraire et généraliser les templates existants :
  - `.install_terraform` amélioré
  - `.setup_ssh` 
  - Nouveau `.terraform_base` pour jobs Terraform
  - Nouveau `.ansible_base` pour jobs Ansible
- Utiliser les anchors YAML et `extends`
- Exemple de template :
```yaml
.terraform_base:
  image: alpine:latest
  extends: .install_terraform
  cache:
    key: "terraform-${CI_COMMIT_REF_SLUG}-${ENV}"
    paths:
      - ${TF_ROOT}/${ENV}/.terraform
  artifacts:
    expire_in: 1 week
  variables:
    GIT_DEPTH: 0
```

**Critères d'acceptation** :
- Fonctionnel : Templates couvrant tous les cas d'usage actuels
- Technique : Utilisation correcte des features GitLab CI (extends, anchors), code DRY

**Criticité** : Haute - Base de la réutilisabilité du nouveau pipeline

**Labels recommandés** : Infrastructure, GitLab CI/CD, Refactoring

**Estimation du temps nécessaire** : 3 heures

**Liens utiles** : GitLab CI/CD job templates documentation

---
