### ISSUE TITLE
Extraire et centraliser les variables globales du pipeline

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#23]
Imported from GitLab:

### Tâche 2

Extraire et centraliser les variables globales du pipeline

**Scope** : CI/CD Pipeline GitLab

**Description fonctionnelle** :
Centraliser toutes les variables globales du pipeline actuel dans un fichier dédié pour améliorer la maintenabilité et éviter les duplications.

**Description technique** :
- Créer `.gitlab/ci/includes/variables.yml`
- Extraire du `.gitlab-ci.yml` actuel :
  - Variables globales (TF_ROOT, TF_VERSION, etc.)
  - Configuration du cache
  - Variables d'optimisation (DOCKER_DRIVER, FF_USE_FASTZIP, etc.)
- Structurer le fichier avec des commentaires explicites
- Exemple de structure :
```yaml
variables:
  # Terraform Configuration
  TF_ROOT: ${CI_PROJECT_DIR}/terraform/environments
  TF_VERSION: "1.12.1"
  
  # Ansible Configuration
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_FORCE_COLOR: "True"
  
  # Performance Optimization
  DOCKER_DRIVER: overlay2
  FF_USE_FASTZIP: "true"

cache:
  key: "terraform-${CI_COMMIT_REF_SLUG}-${ENV:-global}"
  paths:
    - ${TF_ROOT}/${ENV:-**}/.terraform
```

**Critères d'acceptation** :
- Fonctionnel : Toutes les variables extraites et organisées logiquement
- Technique : Fichier YAML valide, commenté, sans duplication

**Criticité** : Haute - Variables essentielles au fonctionnement du pipeline

**Labels recommandés** : Infrastructure, GitLab CI/CD, Refactoring

**Estimation du temps nécessaire** : 2 heures

**Liens utiles** : GitLab CI/CD Variables documentation

---
