### ISSUE TITLE
Refactorisation et factorisation des jobs GitLab CI/CD via templates réutilisables

### ISSUE THREAD

**Issue by Alb06** [Alb06/IaC#25]
Imported from GitLab:

# Refactorisation et factorisation des jobs GitLab CI/CD via templates réutilisables

## Scope
GitLab CI/CD Pipeline (Optimisation et Architecture Modulaire)

## Description fonctionnelle
Refactoriser l'ensemble des jobs GitLab CI/CD pour éliminer la duplication de code en créant des templates réutilisables, améliorer la maintenabilité du pipeline et centraliser la logique commune. Cette refactorisation vise à optimiser la structure modulaire existante en respectant le principe DRY (Don't Repeat Yourself).

### 1. Analyse des duplications actuelles
- **Installation Terraform** : Logic répétée dans tous les jobs Terraform
- **Configuration SSH** : Pattern similaire pour les jobs de synchronisation
- **Gestion des artifacts** : Structure répétitive avec paths et expire_in
- **Rules et conditions** : Règles similaires pour dev/prod/main branch
- **Scripts de validation** : Logique de validation commune
- **Gestion des erreurs** : Pattern de gestion des exit codes

#### `.gitlab/ci/templates/terraform.yml`
```yaml
# Templates spécifiques Terraform
.terraform_base:
  extends: .install_terraform
  image: alpine:latest
  timeout: 3m

.terraform_validate:
  extends: .terraform_base
  stage: validate
  # Logique commune validation

.terraform_plan:
  extends: .terraform_base  
  stage: plan
  # Logique commune planification

.terraform_apply:
  extends: .terraform_base
  stage: apply
  # Logique commune application
```

#### `.gitlab/ci/templates/globals.yml` (nouveau)
```yaml
# Templates génériques cross-technologies
.setup_ssh:
  # Configuration SSH réutilisable

.standard_artifacts:
  # Configuration artifacts standard

.env_rules_dev:
  # Rules pour environnement dev

.env_rules_prod:
  # Rules pour environnement prod

.error_handling:
  # Gestion d'erreurs standard
```

#### `.gitlab/ci/templates/ansible.yml` (nouveau)
```yaml
# Templates spécifiques Ansible
.ansible_base:
  image: cytopia/ansible:latest
  
.ansible_deploy:
  extends: .ansible_base
  stage: deploy
```

### 3. Fichiers à refactoriser
- `jobs/validate/terraform.yml` → Utiliser `.terraform_validate`
- `jobs/plan/terraform.yml` → Utiliser `.terraform_plan`  
- `jobs/apply/terraform.yml` → Utiliser `.terraform_apply`
- `jobs/cleanup/terraform.yml` → Utiliser `.terraform_base`
- `jobs/deploy/ansible.yml` → Utiliser `.ansible_deploy`
- `jobs/sync/github.yml` → Utiliser `.setup_ssh` depuis globals

### 4. Mise à jour des includes
Modifier `.gitlab-ci.yml` pour inclure les nouveaux templates :
```yaml
include:
  - local: '.gitlab/ci/templates/variables.yml'
  - local: '.gitlab/ci/templates/globals.yml'      # NOUVEAU
  - local: '.gitlab/ci/templates/terraform.yml'
  - local: '.gitlab/ci/templates/ansible.yml'     # NOUVEAU
  # ... autres includes jobs
```

### 5. Variables à centraliser
Ajouter dans `variables.yml` :
- Timeouts standards par type de job
- Configurations artifacts communes
- Patterns de rules réutilisables

### 6. Actions spécifiques
1. **Créer** `.gitlab/ci/templates/globals.yml`
2. **Créer** `.gitlab/ci/templates/ansible.yml`
3. **Enrichir** `.gitlab/ci/templates/terraform.yml` avec nouveaux templates
4. **Refactoriser** tous les jobs pour utiliser `extends:`
5. **Supprimer** duplications dans les jobs individuels
6. **Tester** que tous les jobs fonctionnent identiquement
7. **Documenter** les nouveaux templates dans le README

### Fonctionnels
- ✅ Tous les jobs existants fonctionnent exactement comme avant
- ✅ Pipeline s'exécute sans erreur sur dev et prod
- ✅ Artifacts générés identiques à la version précédente
- ✅ Temps d'exécution du pipeline maintenu ou amélioré

### Techniques
- ✅ Réduction d'au moins 40% du code dupliqué
- ✅ Templates réutilisables avec paramètres configurables
- ✅ Organisation logique des templates par technologie
- ✅ Documentation des templates dans commentaires YAML
- ✅ Respect des conventions de nommage GitLab CI
- ✅ Validation syntaxique YAML réussie
- ✅ Tests sur branche de développement avant merge

## Criticité
**Moyenne** - Amélioration technique importante pour la maintenabilité à long terme, sans impact fonctionnel immédiat sur l'infrastructure.

## Labels recommandés
GitLab CI/CD, Refactoring, Infrastructure, DevOps, Templates, DRY

## Estimation du temps nécessaire
**6-8 heures** pour un développeur confirmé
- 2h : Analyse des duplications et conception templates
- 3h : Création/modification des templates  
- 2h : Refactorisation des jobs existants
- 1h : Tests et validation

## Liens utiles
- [GitLab CI/CD Templates Documentation](https://docs.gitlab.com/ee/ci/yaml/#extends)
- [Best Practices GitLab CI/CD](https://docs.gitlab.com/ee/ci/pipelines/pipeline_efficiency.html)
- Repository GitLab : `.gitlab/ci/` structure actuelle
- [YAML Anchors & References](https://docs.gitlab.com/ee/ci/yaml/#anchors)

## Prérequis techniques
- Connaissance approfondie GitLab CI/CD et syntaxe YAML
- Compréhension de la structure pipeline actuelle
- Accès au repository GitLab pour tests sur branche dédiée
- Visual Studio 2022 configuré avec Git

## Livrables attendus
1. **Templates refactorisés** dans `.gitlab/ci/templates/`
2. **Jobs simplifiés** utilisant `extends:`
3. **Documentation** des nouveaux templates
4. **Tests validation** sur environnement dev
5. **Merge Request** avec description détaillée des changements
